controller_list:
  - name: arm_moveit_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - arm_base_to_post
      - arm_inner_to_outer_xy
      - arm_z_slide
      - arm_gripper_rot_z
      - arm_gripper_rot_y
  - name: eef_moveit_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - gripper_base_to_finger_back_left
      - gripper_base_to_finger_back_right
      - gripper_base_to_finger_front_left
      - gripper_base_to_finger_front_right