controller_list:
  - name: fake_arm_controller
    joints:
      - arm_base_to_post
      - arm_inner_to_outer_xy
      - arm_z_slide
      - arm_gripper_rot_z
      - arm_gripper_rot_y
  - name: fake_end_effector_controller
    joints:
      - gripper_base_to_finger_back_left
      - gripper_base_to_finger_back_right
      - gripper_base_to_finger_front_left
      - gripper_base_to_finger_front_right