# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  arm_base_to_post:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  arm_gripper_rot_y:
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: false
    max_acceleration: 0
  arm_gripper_rot_z:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  arm_inner_to_outer_xy:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  arm_z_slide:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_base_to_finger_back_left:
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_base_to_finger_back_right:
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_base_to_finger_front_left:
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_base_to_finger_front_right:
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: false
    max_acceleration: 0