footprint: [[-0.6, -0.35], [0.6, -0.35], [0.6, 0.35], [-0.6, 0.35]]
global_frame: map
transform_tolerance: 2
rolling_window: true
width: 3.5
height: 3.5
resolution: 0.025
origin_x: -1.25
origin_y: -1.25
plugins:
   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

obstacle_layer:
  obstacle_range: 2.5
  raytrace_range: 3
  max_obstacle_height: 2
  track_unknown_space: true

  observation_sources: zed_sensor

  zed_sensor: {
    data_type: PointCloud2,
    topic: "/zed/points",
    expected_update_rate: 0.25,
    marking: true,
    clearing: true,
    min_obstacle_height: 0.06
  }

inflation_layer:
  inflation_radius: 0.1