TrajectoryPlannerROS:
  acc_lim_x: 0.05
  acc_lim_y: 0
  acc_lim_theta: 0.2

  max_vel_x: 1.2
  min_vel_x: 0.1
  max_vel_y: 0
  min_vel_y: 0
  min_in_place_vel_theta: 0.7

  angular_sim_granularity: 0.025

  yaw_goal_tolerance: 1
  xy_goal_tolerance: 0.5

  meter_scoring: true
  holonomic_robot: false

  vtheta_samples: 30

controller_frequency: 30.0

GlobalPlanner:
  allow_unknown: true
