TrajectoryPlannerROS:
  acc_lim_x: 0.2
  acc_lim_y: 0
  acc_lim_theta: 0.5

  max_vel_x: 0.9
  min_vel_x: 0.1
  max_vel_y: 0
  min_vel_y: 0
  min_in_place_vel_theta: 0.8

  yaw_goal_tolerance: 0.7

  meter_scoring: true
  holonomic_robot: false

controller_frequency: 10.0

GlobalPlanner:
  allow_unknown: true
